### ISSUE TITLE
Setup functions can be chosen at the same time

### ISSUE THREAD

**Issue by tfluruby12** [Optoma/optoma-projector-launcher#17]
* setup functions can be chosen at the same time (on emulator)
* no page title
* no yellow edge line 

![screenshot_1496387617](https://cloud.githubusercontent.com/assets/24487101/26714938/450bd3a0-47a6-11e7-813e-7b6b1cd0f85a.png)

**Comment by tfluruby12** [comment]
& no page title

**Comment by kuanyingchou** [comment]
@tfluruby12 We don't yet support mouse. Can you give me the steps to reproduce it?

@giagiar Do we have a title in OSD? Some pictures have it, some have not.

**Comment by giagiar** [comment]
same as settings. Ｗhen in the menu page, there should be tile such as "Settings" and "Projector Setup“ on the top. After entering subpage, remove title and other items should be greyed.
