### ISSUE TITLE
Capitalize the first letter

### ISSUE THREAD

**Issue by tfluruby12** [Optoma/optoma-projector-launcher#18]
* power --> Power
* white line under title should be lower

![screenshot_1496387929](https://cloud.githubusercontent.com/assets/24487101/26715137/12721c32-47a7-11e7-970d-1b8431eea0a1.png)

**Comment by kuanyingchou** [comment]
Fixed. Please see e7f48a9.

**Comment by giagiar** [comment]
please set margin as guideline.  

### 
    <TextView>
        android:layout_marginTop="20dp"
    </TextView>
    <View
        android:id="@+id/setting_divider"
        android:layout_marginTop="66dp"
     />

remember to remove   android:layout_below="@id/setting_textview"

The relative position should be look like this.

<img width="1213" alt="screen shot 2017-06-06 at 18 16 36" src="https://cloud.githubusercontent.com/assets/23302243/26824583/9705a9a6-4ae4-11e7-9406-883e8a02acf4.png">
