### ISSUE TITLE
language setup 

### ISSUE THREAD

**Issue by giagiar** [Optoma/optoma-projector-launcher#5]
。focus on default item

。set the vertical distance as 36dp which already updated on guideline.

<img width="1213" alt="screen shot 2017-05-24 at 18 26 01" src="https://cloud.githubusercontent.com/assets/23302243/26399162/7aeef6ae-40ae-11e7-86d0-55f0daef6b38.png">

**Comment by kuanyingchou** [comment]
For vertical distance, please see 992c23.
